###############################################################################
# This manifest defines a customized NooBaa 'pod-agent' which embeds a Tiering
# Management File System (TMFS) application for handling the migration and the
# recall of data between the 'noobaa-agent' pods (a.k.a. 'backingstore-tmfs'
# or 'bs-tmfs' pods) and a tape library.
#
# In essence, TMFS is a FUSE filesystem that passes the POSIX requests issued
# by NooBaa down to the underlying base filesystem while interfacing with the
# tape library to migrate and recall the data.
#
# NOTES:
#  - We use node anti-affinity rules to spread the BS-TMFS pods while ensuring
#    the scheduling of no more than one BS-TMFS per node.
#  - We use node affinity to solely schedule the BS-TMFS pods on nodes
#    equipped with a host buffer adapter (HBA).
###############################################################################
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: noobaa
  name: noobaa-agent
spec:
  # -------------------------------------------------------------
  # -- AFFINITY
  # -------------------------------------------------------------
  # affinity:
  #   # - We want this pod to be scheduled on a node that is equipped
  #   #   with a host buffer adapter (HBA).
  #   # - The nodes equipped with an HBA are identified by the label 'hba=fc'.
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: hba
  #               operator: In
  #               values:
  #                 - fc

  #   # - We want to place no more than one 'bs-tmfs-X-Y-noobaa-pod-<UID>' pod per node.
  #   # - Every  backingstore pod of type PV-POOL comes with the label 'pool=bs-tmfs-X-Y'
  #   #   (with e.g., X=5, Y=0) that we can use to inform the scheduler.
  #   # - We want this scheduling to be enforced at the node level
  #   #   (.i.e, topological domain = kubernetes.io/hostname)
  #   # - This 'podAntiAffinity' rule complements the scheduler's 'topologySpreadConstraints'
  #   #   rule by strictly preventing to co-locate two such pods on the same node.
  #   # - Warning: For the time being, it does not work with the label 'backingstore=noobaa'
  #   #   because we deploy 5 'bs-tmfs' pods and 1 'noobaa-default-backingstore' pods but
  #   #   we have only 5 nodes.
  #   podAntiAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       - labelSelector:
  #           matchExpressions:
  #             - key: pool
  #               operator: In
  #               values: # [INFO] Prefix match is not supported
  #                 - bs-tmfs-3-0
  #                 - bs-tmfs-3-1
  #                 - bs-tmfs-5-0
  #                 - bs-tmfs-5-1
  #         topologyKey: "kubernetes.io/hostname"

  # -------------------------------------------------------------
  # -- INIT-CONTAINER
  # -------------------------------------------------------------
  # initContainers:
  #   - name: tmfs-agent-init
  #     image: quay.io/fab/alpine-kubectl:1.30  # A lightweight image (71.6MB)
  #     imagePullPolicy: IfNotPresent  # Always
  #     # securityContext:
  #     #   privileged: true
  #     #   capabilities:
  #     #    add:
  #     #       - SYS_ADMIN
  #     command: ['/bin/sh', '-c']
  #     args:
  #       - |
  #         echo "#-- Start of initContainer -------------------------------"
  #         echo
  #         # [OBSOLETE] echo "#-- Create TMFS directories ------------------------------"
  #         # [OBSOLETE] echo "#-- Modify ownership and permissions of the TMFS init file (used in bring-up)"
  #         # [OBSOLETE] chown -R noob:root /tmfs_init_files
  #         # [OBSOLETE]  chmod +x /tmfs_init_files_/tmfs_init.sh
  #         # [TODO-FIXME] Exec 'tmfs_init.sh'
  #         echo
  #         echo "#-- End of initContainer ---------------------------------"
  #     volumeMounts:
  #       - name: tmfs-config-vol
  #         mountPath: /tmfs_config

  # -------------------------------------------------------------
  # -- MAIN-CONTAINER
  # -------------------------------------------------------------
  containers:
    - name: noobaa-agent
      image: NOOBAA_CORE_IMAGE
      imagePullPolicy: Always  # was IfNotPresent
      resources: # ----------------------------------------------
        # https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
        requests:
          cpu: "999m"
          memory: "1Gi"
        limits:
          cpu: "999m"
          memory: "1Gi"
      env: # ----------------------------------------------------
        # Insert the relevant config for the current agent
        - name: CONTAINER_PLATFORM
          value: KUBERNETES
        - name: AGENT_CONFIG
        - name: NOOBAA_LOG_LEVEL
        - name: NOOBAA_LOG_COLOR
        # TMFS-related variables
        - name: BLOCK_STORE_FS_TMFS_ENABLED
          value: "true"
        # Ceph admin keyring
        - name: CEPH_ADMIN_KEY
          valueFrom:
            secretKeyRef:
              name: tmfs-rook-ceph-admin-keyring
              key: rook-ceph-admin-keyring
      command: ["/bin/sh", "-c"]  # -----------------------------
      args: 
        - |
          touch /tmfs_init_files/tmfs_test_init.sh
          echo "#!/bin/sh"                                                 >> /tmfs_init_files/tmfs_test_init.sh
          echo "echo #---------------------------------------------------" >> /tmfs_init_files/tmfs_test_init.sh
          echo "echo #-- Hello from /tmfs_init_files/tmfs_test_init.sh --" >> /tmfs_init_files/tmfs_test_init.sh
          echo "echo #---------------------------------------------------" >> /tmfs_init_files/tmfs_test_init.sh
          chmod +x /tmfs_init_files/tmfs_test_init.sh
          /tmfs_init_files/tmfs_test_init.sh
          echo
          echo "#-- Make the TMFS init files writable during bring-up -----------------"
          cp /tmfs_init_files/tmfs_config/tmfs_init.sh /tmfs_init_files/tmfs_init.sh
          chmod +x /tmfs_init_files/tmfs_init.sh
          echo
          echo "#-- Run 'noobaa_init.sh' in 'tmfs-agent' mode -------------------------"
          /noobaa_init_files/noobaa_init.sh tmfs-agent
          echo
      ports: # --------------------------------------------------
        # This should change according to the allocation from the NooBaa server
        - containerPort: 60101
      volumeMounts: # -------------------------------------------
        # BS-related volumes
        - name: noobaastorage
          mountPath: /noobaa_storage
        - name: tmp-logs-vol
          mountPath: /usr/local/noobaa/logs
        # TMFS-related volumes
        - name: tmfsdbstorage
          mountPath: /tmfs_db
        - name: tmfs-logs-vol
          mountPath: /tmfs_logs
        - name: tmfs-init-vol
          mountPath: /tmfs_init_files
        - name: tmfs-config-vol
          mountPath: /tmfs_init_files/tmfs_config

          # [TO-TRY] Explicitly add and mount host devices to the container
          # [TO-TRY]  (because the container is neither running in privilege mode nor as root)
          # [TO-TRY] - name: dev                     # [20250110] is new
          # [TO-TRY]   mountPath: /dev               # [20250110] is new
          # [TO-TRY]   readOnly: false               # [20250110] is new

      securityContext: # ----------------------------------------
        allowPrivilegeEscalation: true    # was false
        capabilities:                     # is new
          add:                            # is new
            - CAP_SYS_ADMIN               # is new
        privileged: true                  # is new
  automountServiceAccountToken: false
  securityContext:
    runAsUser: 10001
    runAsGroup: 0
    fsGroup: 0
    fsGroupChangePolicy: "OnRootMismatch"
  # -------------------------------------------------------------
  # -- VOLUMES
  # -------------------------------------------------------------
  volumes:
    # BS-related volumes
    - name: tmp-logs-vol
      emptyDir: {}
    - name: noobaastorage
      persistentVolumeClaim:
        claimName: noobaa-pv-claim
    # TMFS-related volumes
    - name: tmfsdbstorage
      persistentVolumeClaim:
        claimName: tmfsdb-pv-claim
    - name: tmfs-logs-vol
      emptyDir: {}
    - name: tmfs-init-vol
      emptyDir: {}
    - name: tmfs-config-vol
      configMap:
        name: tmfs-config


    # [TO-TRY] - name: dev
    # [TO-TRY]   hostPath:
    # [TO-TRY]     path: /dev
