---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: noobaa
  name: noobaa-pv-claim
spec:
  storageClassName: rook-cephfs-1d3m  # 1 DATA replication, 3 METADATA replication 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
