---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: noobaa
    module: db-tmfs
  name: tmfsdb-pv-claim
  namespace: noobaa
persistentVolumeReclaimPolicy: Retain
spec:
  storageClassName: rook-cephfs
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 100Mi  # [TODO] Should be made configurable
